describe('LOGIN', () => {

  it('Honestyemmy', () => 
    {
      cy.visit("https://www.automationexercise.com/");
      cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
      cy.get('[data-qa="login-email"]').type('honestyemmy@gmail.com')
      cy.get('[data-qa="login-password"]').type('emman1992')
      cy.get('[data-qa="login-button"]').click()
      cy.get('.shop-menu > .nav > :nth-child(2) > a').click()
      cy.get(':nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
      cy.get('.modal-footer > .btn').click()
      cy.get(':nth-child(4) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
      cy.get('.modal-footer > .btn').click()
      cy.get(':nth-child(5) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
      cy.get('.modal-footer > .btn').click()
      cy.get(':nth-child(6) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
      cy.get('.modal-footer > .btn').click()
      cy.get(':nth-child(10) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
      cy.get('.modal-footer > .btn').click()
      cy.get(':nth-child(8) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
      cy.get('u').click()
      cy.get('.col-sm-6 > .btn').click()
      cy.get(':nth-child(7) > .btn').click()
      cy.get('[data-qa="name-on-card"]').type('adeniyi emmanuel')
      cy.get('[data-qa="card-number"]').type('1234567891234567')
      cy.get('[data-qa="cvc"]').type('456')
      cy.get('[data-qa="expiry-month"]').type('09')
      cy.get('[data-qa="expiry-year"]').type('3565')
      cy.get('[data-qa="pay-button"]').click()
      cy.get('[data-qa="continue-button"]').click()
      cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
  })
})