let el
describe('POM FIXTURE 1', ()=>{
    beforeEach(()=>{
        cy.visit('/')
        cy.title().should('equal','Swag Labs')
        cy.fixture('example').then((sel)=>{
            el=sel
        })
    })

    it('VERIFY USER CAN LOGIN SUCCESSFULLY', ()=>{
           cy.get(el.usernameField).type(el.standardUser)
           cy.get(el.passwordField).type(el.password)
           cy.get(el.loginButton).click()

    })
    it('VERIFY USER CANNOT LOGIN WITH INVALID PASSWORD', ()=>{
          cy.get(el.usernameField).type(el.standardUser)
          cy.get(el.passwordField).type(el.invalidPassword)
          cy.get(el.loginButton).click()
        
   })
   it('VERIFY USER CAN ADD ITEMS TO CARTS', ()=>{
      cy.get(el.usernameField).type(el.standardUser)
      cy.get(el.passwordField).type(el.password)
      cy.get(el.loginButton).click()
      cy.get(el.backPack).click()
      cy.get(el.bikeLight).click()
      cy.get(el.boltTshirt).click()
      cy.get(el.fleeceJacket).click()
      cy.get(el.oneSie).click()
      cy.get(el.redTshirt).click()
    
})
it('VERIFY USER CAN VIEW THE SHOPPINGCART ', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
  
})

it('VERIFY USER CAN CHECKOUT', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
  
})
it('VERIFY USER CAN ADD THEIR FIRSTNAME', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
    cy.get(el.firstNameField).type('ADE')
  
})
it('VERIFY USER CAN ADD THEIR LASTNAME', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
    cy.get(el.firstNameField).type('ADE')
    cy.get(el.lastNameField).type('EMMANUEL')
  
})
it('VERIFY USER CAN ADD THEIR ZIPCODE', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
    cy.get(el.firstNameField).type('ADE')
    cy.get(el.lastNameField).type('EMMANUEL')
    cy.get(el.zipCodeField).type('1000002')
  
})
it('VERIFY USER CAN CONTINUE', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
    cy.get(el.firstNameField).type('ADE')
    cy.get(el.lastNameField).type('EMMANUEL')
    cy.get(el.zipCodeField).type('1000002')
    cy.get(el.continue).click()

})

it('VERIFY USER CAN CLICK ON FINISH', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
    cy.get(el.firstNameField).type('ADE')
    cy.get(el.lastNameField).type('EMMANUEL')
    cy.get(el.zipCodeField).type('1000002')
    cy.get(el.continue).click()
    cy.get(el.finish).click()
  
})

it('VERIFY USER CAN BACK HOME', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
    cy.get(el.firstNameField).type('ADE')
    cy.get(el.lastNameField).type('EMMANUEL')
    cy.get(el.zipCodeField).type('1000002')
    cy.get(el.continue).click()
    cy.get(el.finish).click()
    cy.get(el.backToproduct).click()
  
})

it('VERIFY USER CAN CLICK THE HOME OPTIONS', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
    cy.get(el.firstNameField).type('ADE')
    cy.get(el.lastNameField).type('EMMANUEL')
    cy.get(el.zipCodeField).type('1000002')
    cy.get(el.continue).click()
    cy.get(el.finish).click()
    cy.get(el.backToproduct).click()
    cy.get(el.selectButton).click()
  
})

it('VERIFY USER CAN LOG OUT', ()=>{
    cy.get(el.usernameField).type(el.standardUser)
    cy.get(el.passwordField).type(el.password)
    cy.get(el.loginButton).click()
    cy.get(el.backPack).click()
    cy.get(el.bikeLight).click()
    cy.get(el.boltTshirt).click()
    cy.get(el.fleeceJacket).click()
    cy.get(el.oneSie).click()
    cy.get(el.redTshirt).click()
    cy.get(el.shoppingCart).click()
    cy.get(el.checkout).click()
    cy.get(el.firstNameField).type('ADE')
    cy.get(el.lastNameField).type('EMMANUEL')
    cy.get(el.zipCodeField).type('1000002')
    cy.get(el.continue).click()
    cy.get(el.finish).click()
    cy.get(el.backToproduct).click()
    cy.get(el.selectButton).click()
    cy.get(el.logOut).click()

})
})